#!/bin/bash

# Hide 'last login' line when starting a new terminal session
touch $HOME/.hushlogin

echo 'Install oh-my-zsh'
echo '-----------------'
rm -rf $HOME/.oh-my-zsh
curl -L https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sh

# Add global gitignore
ln -s $HOME/.dotfiles/shell/.global-gitignore $HOME/.global-gitignore
git config --global core.excludesfile $HOME/.global-gitignore

# Symlink zsh prefs
rm $HOME/.zshrc
ln -s $HOME/.dotfiles/shell/.zshrc $HOME/.zshrc
ln -s $HOME/.dotfiles/shell/kenton.zsh-theme $HOME/.oh-my-zsh/themes/kenton.zsh-theme

echo 'Install homebrew'
echo '----------------'
sudo rm -rf /usr/local/Cellar /usr/local/.git && brew cleanup
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"

echo 'Install coreutils'
echo '-----------------'
brew install coreutils

echo 'Install git'
echo '-----------'
brew install wget git

echo 'Install curl'
echo '------------'
brew install curl

echo 'Install brew-cask'
echo '-----------------'
brew tap homebrew/cask
brew install brew-cask

echo 'Install imagemagick'
echo '-------------------'
brew install imagemagick

echo 'Download ASDF'
echo '-------------'
rm -rf $HOME/.asdf
git clone https://github.com/asdf-vm/asdf.git $HOME/.asdf --branch v0.13.1

echo 'Install ASDF'
echo '------------'
echo '. "$HOME/.asdf/asdf.sh"' >> $HOME/.zshrc
echo '. "$HOME/.asdf/completions/asdf.bash"' >> $HOME/.zshrc
echo 'legacy_version_file = yes' >> $HOME/.asdfrc
exec $SHELL

echo 'Install latest Ruby'
echo '-------------------'
asdf plugin add ruby
asdf install ruby latest
asdf global ruby latest

echo 'Install latest Node'
echo '-------------------'
asdf plugin add nodejs
asdf install nodejs latest
asdf global nodejs latest

echo 'Configure npm'
echo '-------------'
# Create a directory for global packages and tell npm where to store globally installed packages
mkdir "${HOME}/.npm-packages"
npm config set prefix "${HOME}/.npm-packages"

echo 'Configure git'
echo '-------------'
git config --global color.ui true
git config --global user.name "Kenton Glass"
git config --global user.email "git@kenton.glass"
git config --global push.default current
git config --global push.autosetupremote true
git config --global init.defaultbranch main
git config --global gt.exclude staging

echo 'Install git-trim'
echo '----------------'
git clone https://github.com/jasonmccreary/git-trim.git $ZSH_CUSTOM/plugins/git-trim

echo '++++++++++++++++++++++++++++++'
echo '++++++++++++++++++++++++++++++'
echo 'All done!'
echo '++++++++++++++++++++++++++++++'
